CREATE TABLE portfolio (
    id INT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cod VARCHAR(100) NOT NULL,
    companyName VARCHAR(100) NOT NULL,
    qtt VARCHAR(100) NOT NULL,
    price VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;